language: go
sudo: false
go:
  - 1.5
  - 1.6

addons:
  apt:
    packages:
      - mysql-server-5.6
      - mysql-client-core-5.6
      - mysql-client-5.6

before_install:
  - go get github.com/onsi/gomega
  - go get github.com/onsi/ginkgo
  - go get golang.org/x/tools/cmd/cover

before_script:
  - mysql -u root -e 'create database gotest;'

script:
  - ./test.sh 

after_success:
  - bash <(curl -s https://codecov.io/bash)
