global:
  port: 4306
  manage_port: 4307
  max_connections: 10
  log_filename: ./log/dbatman.log
  log_level: 1
  log_maxsize: 1024
  log_query_min_time: 0
  client_timeout: 1800
  server_timeout: 1800
  write_time_interval: 10
  conf_autoload: 1
  authip_active: false 
  auth_ips:
    - 10.4.64.1
    - 10.4.64.2
clusters:
  test_cluster:
    master:
      host: 127.0.0.1
      port: 3306
      username: root
      password:
      dbname: client_test_db
      charset: utf8mb4
      weight: 1
      max_connections: 100
      max_connection_pool_size: 10
      connect_timeout: 10
      time_reconnect_interval: 10
    slaves:
    - host: 127.0.0.1
      port: 3306
      username: root
      password: 
      dbname: client_test_db
      charset: utf8mb4
      weight: 1
      max_connections: 100
      max_connection_pool_size: 10
      connect_timeout: 10
      time_reconnect_interval: 10
users:
  proxy_test_user:
    username: proxy_test_user
    password: test
    dbname: client_test_db
    charset: utf8mb4
    max_connections: 1000
    min_connections: 100
    cluster_name: test_cluster
    auth_ips:
    - 10.1.1.1
    - 10.1.1.2
    black_list_ips:
    - 10.1.1.3
    - 10.1.1.4
